<?php

declare(strict_types=1);

namespace FancyPasskeys\Support;

/**
 * Where PHP is made to agree with the Node twin.
 *
 * `web-auth/webauthn-lib`'s serializer already emits the W3C `…JSON` shapes —
 * base64url `challenge`, `user.id`, and descriptor `id` fields — so the browser
 * accepts its output unchanged. It is not, however, *identical* to what
 * `@simplewebauthn/server` emits for the same inputs, and "not identical" is
 * how a matched pair quietly stops being a pair: the React surface starts
 * depending on a field only one backend sends, and the other backend's users
 * find out in production.
 *
 * The three differences, all additive:
 *
 * 1. `authenticatorSelection.requireResidentKey` — the WebAuthn L1 boolean that
 *    L2 replaced with `residentKey`. SimpleWebAuthn still emits it (spec:
 *    "Relying Parties SHOULD set it to true if, and only if, residentKey is set
 *    to required"); webauthn-lib emits it only when it is `true`.
 * 2. `extensions.credProps` — requested on registration so the browser reports
 *    back whether the credential is actually discoverable.
 * 3. `hints` — an empty list rather than an absent key, so a client can read
 *    `options.hints.length` without a guard.
 *
 * Every method here is a pure array→array transform, which is what makes
 * `WireParityTest` able to assert the result against a fixture generated by the
 * Node package itself.
 */
final class WireFormat
{
    /**
     * @param  array<string, mixed>  $serialized  Decoded `PublicKeyCredentialCreationOptions`.
     * @return array<string, mixed> `PublicKeyCredentialCreationOptionsJSON`
     */
    public static function creationOptions(array $serialized): array
    {
        $selection = $serialized['authenticatorSelection'] ?? [];
        $selection = is_array($selection) ? $selection : [];

        $residentKey = $selection['residentKey'] ?? null;
        $selection['requireResidentKey'] = $residentKey === 'required';

        $extensions = $serialized['extensions'] ?? [];
        $extensions = is_array($extensions) ? $extensions : [];
        $extensions['credProps'] = true;

        $serialized['authenticatorSelection'] = $selection;
        $serialized['extensions'] = $extensions;
        $serialized['excludeCredentials'] = self::descriptors($serialized['excludeCredentials'] ?? []);
        $serialized['hints'] = array_values((array) ($serialized['hints'] ?? []));

        return $serialized;
    }

    /**
     * @param  array<string, mixed>  $serialized  Decoded `PublicKeyCredentialRequestOptions`.
     * @return array<string, mixed> `PublicKeyCredentialRequestOptionsJSON`
     */
    public static function requestOptions(array $serialized): array
    {
        $serialized['allowCredentials'] = self::descriptors($serialized['allowCredentials'] ?? []);

        // SimpleWebAuthn omits `extensions` from authentication options unless
        // the caller passed some, and omits `hints` entirely. Matching means
        // *not* inventing keys here.
        if (($serialized['extensions'] ?? null) === [] || ($serialized['extensions'] ?? null) === null) {
            unset($serialized['extensions']);
        }

        unset($serialized['hints']);

        return $serialized;
    }

    /**
     * Descriptors must be a JSON array even when empty — `{}` here breaks
     * `navigator.credentials.*` and is what an associative PHP array encodes to.
     *
     * @param  mixed  $descriptors
     * @return list<array<string, mixed>>
     */
    private static function descriptors(mixed $descriptors): array
    {
        if (! is_array($descriptors)) {
            return [];
        }

        return array_values(array_map(
            static function (mixed $descriptor): array {
                $descriptor = is_array($descriptor) ? $descriptor : [];
                $descriptor['type'] = 'public-key';

                return $descriptor;
            },
            $descriptors,
        ));
    }
}
